# Configuración general
spring.profiles.active=test
spring.application.name=FunkoSB
server.port=8080
spring.web.locale=es_ES
spring.web.locale-resolver=fixed
server.error.include-message=always

# Base de datos H2 en memoria para pruebas
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.cache.type=simple

# Configuración del banner
spring.banner.location=classpath:banner.txt
spring.main.banner-mode=console

# Configuración de carga de archivos (si es necesario para tus pruebas)
upload.root-location=imgs
upload.delete=true

# API version
api.version=v1

# Configuración de perfiles para pruebas (si es necesario)
# spring.profiles.active=test
