# Configuración general
spring.profiles.active=test
spring.application.name=FunkoSB
server.port=8080
spring.web.locale=es_ES
spring.web.locale-resolver=fixed
server.error.include-message=always
jwt.secret=tu-secreto-super-seguro
jwt.expiration=86400


# Desactivar H2 para pruebas
spring.h2.console.enabled=false
spring.jpa.enabled=false

# Eliminar configuración de H2 (ya no es necesaria)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.username=root
# spring.datasource.password=root
# spring.datasource.driver-class-name=org.h2.Driver
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.show-sql=true

# Configuración de MongoDB para pruebas
spring.data.mongodb.uri=mongodb://localhost:27017/testdb

# Configuración de cache
spring.cache.type=simple

# Configuración del banner
spring.banner.location=classpath:banner.txt
spring.main.banner-mode=console

# Configuración de carga de archivos (si es necesario para tus pruebas)
upload.root-location=imgs
upload.delete=true

# API version
api.version=v1

# JWT
token.signing.key=secret
token.expiration.time=86400