spring.application.name=FunkoSB
server.port=8080
spring.web.locale=es_ES
spring.web.locale-resolver=fixed
server.error.include-message=always

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.cache.type=simple

spring.banner.location=classpath:banner.txt
spring.main.banner-mode=console

upload.root-location=imgs
upload.delete=true

api.version=v1
